#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBongDa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyGiaiDau")]
	public partial class DBGiaiDauDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCauThu(CauThu instance);
    partial void UpdateCauThu(CauThu instance);
    partial void DeleteCauThu(CauThu instance);
    partial void InsertChiTietTranDau(ChiTietTranDau instance);
    partial void UpdateChiTietTranDau(ChiTietTranDau instance);
    partial void DeleteChiTietTranDau(ChiTietTranDau instance);
    partial void InsertDoiBong(DoiBong instance);
    partial void UpdateDoiBong(DoiBong instance);
    partial void DeleteDoiBong(DoiBong instance);
    partial void InsertGiaiDau(GiaiDau instance);
    partial void UpdateGiaiDau(GiaiDau instance);
    partial void DeleteGiaiDau(GiaiDau instance);
    partial void InsertHuanLuyenVien(HuanLuyenVien instance);
    partial void UpdateHuanLuyenVien(HuanLuyenVien instance);
    partial void DeleteHuanLuyenVien(HuanLuyenVien instance);
    partial void InsertTranDau(TranDau instance);
    partial void UpdateTranDau(TranDau instance);
    partial void DeleteTranDau(TranDau instance);
    partial void InsertTrongTai(TrongTai instance);
    partial void UpdateTrongTai(TrongTai instance);
    partial void DeleteTrongTai(TrongTai instance);
    partial void InserttDanhGia(tDanhGia instance);
    partial void UpdatetDanhGia(tDanhGia instance);
    partial void DeletetDanhGia(tDanhGia instance);
    partial void InserttTaiKhoan(tTaiKhoan instance);
    partial void UpdatetTaiKhoan(tTaiKhoan instance);
    partial void DeletetTaiKhoan(tTaiKhoan instance);
    partial void InsertVoteCLB(VoteCLB instance);
    partial void UpdateVoteCLB(VoteCLB instance);
    partial void DeleteVoteCLB(VoteCLB instance);
    #endregion
		
		public DBGiaiDauDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyGiaiDauConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBGiaiDauDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBGiaiDauDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBGiaiDauDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBGiaiDauDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CauThu> CauThus
		{
			get
			{
				return this.GetTable<CauThu>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietTranDau> ChiTietTranDaus
		{
			get
			{
				return this.GetTable<ChiTietTranDau>();
			}
		}
		
		public System.Data.Linq.Table<DoiBong> DoiBongs
		{
			get
			{
				return this.GetTable<DoiBong>();
			}
		}
		
		public System.Data.Linq.Table<GiaiDau> GiaiDaus
		{
			get
			{
				return this.GetTable<GiaiDau>();
			}
		}
		
		public System.Data.Linq.Table<HuanLuyenVien> HuanLuyenViens
		{
			get
			{
				return this.GetTable<HuanLuyenVien>();
			}
		}
		
		public System.Data.Linq.Table<TranDau> TranDaus
		{
			get
			{
				return this.GetTable<TranDau>();
			}
		}
		
		public System.Data.Linq.Table<TrongTai> TrongTais
		{
			get
			{
				return this.GetTable<TrongTai>();
			}
		}
		
		public System.Data.Linq.Table<tDanhGia> tDanhGias
		{
			get
			{
				return this.GetTable<tDanhGia>();
			}
		}
		
		public System.Data.Linq.Table<tTaiKhoan> tTaiKhoans
		{
			get
			{
				return this.GetTable<tTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<VoteCLB> VoteCLBs
		{
			get
			{
				return this.GetTable<VoteCLB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauThu")]
	public partial class CauThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCauThu;
		
		private string _HoTenCauThu;
		
		private string _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _SoAo;
		
		private string _ViTri;
		
		private string _MaDoiBong;
		
		private EntityRef<DoiBong> _DoiBong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauThuChanging(string value);
    partial void OnMaCauThuChanged();
    partial void OnHoTenCauThuChanging(string value);
    partial void OnHoTenCauThuChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnSoAoChanging(string value);
    partial void OnSoAoChanged();
    partial void OnViTriChanging(string value);
    partial void OnViTriChanged();
    partial void OnMaDoiBongChanging(string value);
    partial void OnMaDoiBongChanged();
    #endregion
		
		public CauThu()
		{
			this._DoiBong = default(EntityRef<DoiBong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauThu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCauThu
		{
			get
			{
				return this._MaCauThu;
			}
			set
			{
				if ((this._MaCauThu != value))
				{
					this.OnMaCauThuChanging(value);
					this.SendPropertyChanging();
					this._MaCauThu = value;
					this.SendPropertyChanged("MaCauThu");
					this.OnMaCauThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenCauThu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenCauThu
		{
			get
			{
				return this._HoTenCauThu;
			}
			set
			{
				if ((this._HoTenCauThu != value))
				{
					this.OnHoTenCauThuChanging(value);
					this.SendPropertyChanging();
					this._HoTenCauThu = value;
					this.SendPropertyChanged("HoTenCauThu");
					this.OnHoTenCauThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NChar(10)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoAo", DbType="NChar(10)")]
		public string SoAo
		{
			get
			{
				return this._SoAo;
			}
			set
			{
				if ((this._SoAo != value))
				{
					this.OnSoAoChanging(value);
					this.SendPropertyChanging();
					this._SoAo = value;
					this.SendPropertyChanged("SoAo");
					this.OnSoAoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="NChar(10)")]
		public string ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiBong", DbType="NChar(10)")]
		public string MaDoiBong
		{
			get
			{
				return this._MaDoiBong;
			}
			set
			{
				if ((this._MaDoiBong != value))
				{
					if (this._DoiBong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoiBongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiBong = value;
					this.SendPropertyChanged("MaDoiBong");
					this.OnMaDoiBongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiBong_CauThu", Storage="_DoiBong", ThisKey="MaDoiBong", OtherKey="MaDoiBong", IsForeignKey=true)]
		public DoiBong DoiBong
		{
			get
			{
				return this._DoiBong.Entity;
			}
			set
			{
				DoiBong previousValue = this._DoiBong.Entity;
				if (((previousValue != value) 
							|| (this._DoiBong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoiBong.Entity = null;
						previousValue.CauThus.Remove(this);
					}
					this._DoiBong.Entity = value;
					if ((value != null))
					{
						value.CauThus.Add(this);
						this._MaDoiBong = value.MaDoiBong;
					}
					else
					{
						this._MaDoiBong = default(string);
					}
					this.SendPropertyChanged("DoiBong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietTranDau")]
	public partial class ChiTietTranDau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _BanThang;
		
		private System.Nullable<int> _TheVang;
		
		private System.Nullable<int> _TheDo;
		
		private string _MaTranDau;
		
		private string _MaDoi;
		
		private EntityRef<DoiBong> _DoiBong;
		
		private EntityRef<TranDau> _TranDau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBanThangChanging(System.Nullable<int> value);
    partial void OnBanThangChanged();
    partial void OnTheVangChanging(System.Nullable<int> value);
    partial void OnTheVangChanged();
    partial void OnTheDoChanging(System.Nullable<int> value);
    partial void OnTheDoChanged();
    partial void OnMaTranDauChanging(string value);
    partial void OnMaTranDauChanged();
    partial void OnMaDoiChanging(string value);
    partial void OnMaDoiChanged();
    #endregion
		
		public ChiTietTranDau()
		{
			this._DoiBong = default(EntityRef<DoiBong>);
			this._TranDau = default(EntityRef<TranDau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BanThang", DbType="Int")]
		public System.Nullable<int> BanThang
		{
			get
			{
				return this._BanThang;
			}
			set
			{
				if ((this._BanThang != value))
				{
					this.OnBanThangChanging(value);
					this.SendPropertyChanging();
					this._BanThang = value;
					this.SendPropertyChanged("BanThang");
					this.OnBanThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheVang", DbType="Int")]
		public System.Nullable<int> TheVang
		{
			get
			{
				return this._TheVang;
			}
			set
			{
				if ((this._TheVang != value))
				{
					this.OnTheVangChanging(value);
					this.SendPropertyChanging();
					this._TheVang = value;
					this.SendPropertyChanged("TheVang");
					this.OnTheVangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheDo", DbType="Int")]
		public System.Nullable<int> TheDo
		{
			get
			{
				return this._TheDo;
			}
			set
			{
				if ((this._TheDo != value))
				{
					this.OnTheDoChanging(value);
					this.SendPropertyChanging();
					this._TheDo = value;
					this.SendPropertyChanged("TheDo");
					this.OnTheDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTranDau", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaTranDau
		{
			get
			{
				return this._MaTranDau;
			}
			set
			{
				if ((this._MaTranDau != value))
				{
					if (this._TranDau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTranDauChanging(value);
					this.SendPropertyChanging();
					this._MaTranDau = value;
					this.SendPropertyChanged("MaTranDau");
					this.OnMaTranDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoi", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoi
		{
			get
			{
				return this._MaDoi;
			}
			set
			{
				if ((this._MaDoi != value))
				{
					if (this._DoiBong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoiChanging(value);
					this.SendPropertyChanging();
					this._MaDoi = value;
					this.SendPropertyChanged("MaDoi");
					this.OnMaDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiBong_ChiTietTranDau", Storage="_DoiBong", ThisKey="MaDoi", OtherKey="MaDoiBong", IsForeignKey=true)]
		public DoiBong DoiBong
		{
			get
			{
				return this._DoiBong.Entity;
			}
			set
			{
				DoiBong previousValue = this._DoiBong.Entity;
				if (((previousValue != value) 
							|| (this._DoiBong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoiBong.Entity = null;
						previousValue.ChiTietTranDau = null;
					}
					this._DoiBong.Entity = value;
					if ((value != null))
					{
						value.ChiTietTranDau = this;
						this._MaDoi = value.MaDoiBong;
					}
					else
					{
						this._MaDoi = default(string);
					}
					this.SendPropertyChanged("DoiBong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TranDau_ChiTietTranDau", Storage="_TranDau", ThisKey="MaTranDau", OtherKey="MaTranDau", IsForeignKey=true)]
		public TranDau TranDau
		{
			get
			{
				return this._TranDau.Entity;
			}
			set
			{
				TranDau previousValue = this._TranDau.Entity;
				if (((previousValue != value) 
							|| (this._TranDau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TranDau.Entity = null;
						previousValue.ChiTietTranDaus.Remove(this);
					}
					this._TranDau.Entity = value;
					if ((value != null))
					{
						value.ChiTietTranDaus.Add(this);
						this._MaTranDau = value.MaTranDau;
					}
					else
					{
						this._MaTranDau = default(string);
					}
					this.SendPropertyChanged("TranDau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoiBong")]
	public partial class DoiBong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoiBong;
		
		private string _TenDoi;
		
		private string _MaGiaiDau;
		
		private string _MaHLV;
		
		private EntitySet<CauThu> _CauThus;
		
		private EntityRef<ChiTietTranDau> _ChiTietTranDau;
		
		private EntityRef<GiaiDau> _GiaiDau;
		
		private EntityRef<HuanLuyenVien> _HuanLuyenVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoiBongChanging(string value);
    partial void OnMaDoiBongChanged();
    partial void OnTenDoiChanging(string value);
    partial void OnTenDoiChanged();
    partial void OnMaGiaiDauChanging(string value);
    partial void OnMaGiaiDauChanged();
    partial void OnMaHLVChanging(string value);
    partial void OnMaHLVChanged();
    #endregion
		
		public DoiBong()
		{
			this._CauThus = new EntitySet<CauThu>(new Action<CauThu>(this.attach_CauThus), new Action<CauThu>(this.detach_CauThus));
			this._ChiTietTranDau = default(EntityRef<ChiTietTranDau>);
			this._GiaiDau = default(EntityRef<GiaiDau>);
			this._HuanLuyenVien = default(EntityRef<HuanLuyenVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiBong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoiBong
		{
			get
			{
				return this._MaDoiBong;
			}
			set
			{
				if ((this._MaDoiBong != value))
				{
					this.OnMaDoiBongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiBong = value;
					this.SendPropertyChanged("MaDoiBong");
					this.OnMaDoiBongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDoi
		{
			get
			{
				return this._TenDoi;
			}
			set
			{
				if ((this._TenDoi != value))
				{
					this.OnTenDoiChanging(value);
					this.SendPropertyChanging();
					this._TenDoi = value;
					this.SendPropertyChanged("TenDoi");
					this.OnTenDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaiDau", DbType="NChar(10)")]
		public string MaGiaiDau
		{
			get
			{
				return this._MaGiaiDau;
			}
			set
			{
				if ((this._MaGiaiDau != value))
				{
					if (this._GiaiDau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiaiDauChanging(value);
					this.SendPropertyChanging();
					this._MaGiaiDau = value;
					this.SendPropertyChanged("MaGiaiDau");
					this.OnMaGiaiDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHLV", DbType="NChar(10)")]
		public string MaHLV
		{
			get
			{
				return this._MaHLV;
			}
			set
			{
				if ((this._MaHLV != value))
				{
					if (this._HuanLuyenVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHLVChanging(value);
					this.SendPropertyChanging();
					this._MaHLV = value;
					this.SendPropertyChanged("MaHLV");
					this.OnMaHLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiBong_CauThu", Storage="_CauThus", ThisKey="MaDoiBong", OtherKey="MaDoiBong")]
		public EntitySet<CauThu> CauThus
		{
			get
			{
				return this._CauThus;
			}
			set
			{
				this._CauThus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiBong_ChiTietTranDau", Storage="_ChiTietTranDau", ThisKey="MaDoiBong", OtherKey="MaDoi", IsUnique=true, IsForeignKey=false)]
		public ChiTietTranDau ChiTietTranDau
		{
			get
			{
				return this._ChiTietTranDau.Entity;
			}
			set
			{
				ChiTietTranDau previousValue = this._ChiTietTranDau.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietTranDau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietTranDau.Entity = null;
						previousValue.DoiBong = null;
					}
					this._ChiTietTranDau.Entity = value;
					if ((value != null))
					{
						value.DoiBong = this;
					}
					this.SendPropertyChanged("ChiTietTranDau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaiDau_DoiBong", Storage="_GiaiDau", ThisKey="MaGiaiDau", OtherKey="MaGiaiDau", IsForeignKey=true)]
		public GiaiDau GiaiDau
		{
			get
			{
				return this._GiaiDau.Entity;
			}
			set
			{
				GiaiDau previousValue = this._GiaiDau.Entity;
				if (((previousValue != value) 
							|| (this._GiaiDau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaiDau.Entity = null;
						previousValue.DoiBongs.Remove(this);
					}
					this._GiaiDau.Entity = value;
					if ((value != null))
					{
						value.DoiBongs.Add(this);
						this._MaGiaiDau = value.MaGiaiDau;
					}
					else
					{
						this._MaGiaiDau = default(string);
					}
					this.SendPropertyChanged("GiaiDau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HuanLuyenVien_DoiBong", Storage="_HuanLuyenVien", ThisKey="MaHLV", OtherKey="MaHLV", IsForeignKey=true)]
		public HuanLuyenVien HuanLuyenVien
		{
			get
			{
				return this._HuanLuyenVien.Entity;
			}
			set
			{
				HuanLuyenVien previousValue = this._HuanLuyenVien.Entity;
				if (((previousValue != value) 
							|| (this._HuanLuyenVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HuanLuyenVien.Entity = null;
						previousValue.DoiBongs.Remove(this);
					}
					this._HuanLuyenVien.Entity = value;
					if ((value != null))
					{
						value.DoiBongs.Add(this);
						this._MaHLV = value.MaHLV;
					}
					else
					{
						this._MaHLV = default(string);
					}
					this.SendPropertyChanged("HuanLuyenVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CauThus(CauThu entity)
		{
			this.SendPropertyChanging();
			entity.DoiBong = this;
		}
		
		private void detach_CauThus(CauThu entity)
		{
			this.SendPropertyChanging();
			entity.DoiBong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaiDau")]
	public partial class GiaiDau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaiDau;
		
		private string _TenGiaiDau;
		
		private int _SoLuongDoi;
		
		private string _TheThucThiDau;
		
		private bool _GioiTinh;
		
		private System.Nullable<int> _TheLoaiSan;
		
		private EntitySet<DoiBong> _DoiBongs;
		
		private EntitySet<TranDau> _TranDaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaiDauChanging(string value);
    partial void OnMaGiaiDauChanged();
    partial void OnTenGiaiDauChanging(string value);
    partial void OnTenGiaiDauChanged();
    partial void OnSoLuongDoiChanging(int value);
    partial void OnSoLuongDoiChanged();
    partial void OnTheThucThiDauChanging(string value);
    partial void OnTheThucThiDauChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnTheLoaiSanChanging(System.Nullable<int> value);
    partial void OnTheLoaiSanChanged();
    #endregion
		
		public GiaiDau()
		{
			this._DoiBongs = new EntitySet<DoiBong>(new Action<DoiBong>(this.attach_DoiBongs), new Action<DoiBong>(this.detach_DoiBongs));
			this._TranDaus = new EntitySet<TranDau>(new Action<TranDau>(this.attach_TranDaus), new Action<TranDau>(this.detach_TranDaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaiDau", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaiDau
		{
			get
			{
				return this._MaGiaiDau;
			}
			set
			{
				if ((this._MaGiaiDau != value))
				{
					this.OnMaGiaiDauChanging(value);
					this.SendPropertyChanging();
					this._MaGiaiDau = value;
					this.SendPropertyChanged("MaGiaiDau");
					this.OnMaGiaiDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiaiDau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGiaiDau
		{
			get
			{
				return this._TenGiaiDau;
			}
			set
			{
				if ((this._TenGiaiDau != value))
				{
					this.OnTenGiaiDauChanging(value);
					this.SendPropertyChanging();
					this._TenGiaiDau = value;
					this.SendPropertyChanged("TenGiaiDau");
					this.OnTenGiaiDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDoi", DbType="Int NOT NULL")]
		public int SoLuongDoi
		{
			get
			{
				return this._SoLuongDoi;
			}
			set
			{
				if ((this._SoLuongDoi != value))
				{
					this.OnSoLuongDoiChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDoi = value;
					this.SendPropertyChanged("SoLuongDoi");
					this.OnSoLuongDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheThucThiDau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TheThucThiDau
		{
			get
			{
				return this._TheThucThiDau;
			}
			set
			{
				if ((this._TheThucThiDau != value))
				{
					this.OnTheThucThiDauChanging(value);
					this.SendPropertyChanging();
					this._TheThucThiDau = value;
					this.SendPropertyChanged("TheThucThiDau");
					this.OnTheThucThiDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoaiSan", DbType="Int")]
		public System.Nullable<int> TheLoaiSan
		{
			get
			{
				return this._TheLoaiSan;
			}
			set
			{
				if ((this._TheLoaiSan != value))
				{
					this.OnTheLoaiSanChanging(value);
					this.SendPropertyChanging();
					this._TheLoaiSan = value;
					this.SendPropertyChanged("TheLoaiSan");
					this.OnTheLoaiSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaiDau_DoiBong", Storage="_DoiBongs", ThisKey="MaGiaiDau", OtherKey="MaGiaiDau")]
		public EntitySet<DoiBong> DoiBongs
		{
			get
			{
				return this._DoiBongs;
			}
			set
			{
				this._DoiBongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaiDau_TranDau", Storage="_TranDaus", ThisKey="MaGiaiDau", OtherKey="MaGiaiDau")]
		public EntitySet<TranDau> TranDaus
		{
			get
			{
				return this._TranDaus;
			}
			set
			{
				this._TranDaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoiBongs(DoiBong entity)
		{
			this.SendPropertyChanging();
			entity.GiaiDau = this;
		}
		
		private void detach_DoiBongs(DoiBong entity)
		{
			this.SendPropertyChanging();
			entity.GiaiDau = null;
		}
		
		private void attach_TranDaus(TranDau entity)
		{
			this.SendPropertyChanging();
			entity.GiaiDau = this;
		}
		
		private void detach_TranDaus(TranDau entity)
		{
			this.SendPropertyChanging();
			entity.GiaiDau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HuanLuyenVien")]
	public partial class HuanLuyenVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHLV;
		
		private string _TenHLV;
		
		private string _NgaySinh;
		
		private EntitySet<DoiBong> _DoiBongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHLVChanging(string value);
    partial void OnMaHLVChanged();
    partial void OnTenHLVChanging(string value);
    partial void OnTenHLVChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public HuanLuyenVien()
		{
			this._DoiBongs = new EntitySet<DoiBong>(new Action<DoiBong>(this.attach_DoiBongs), new Action<DoiBong>(this.detach_DoiBongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHLV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHLV
		{
			get
			{
				return this._MaHLV;
			}
			set
			{
				if ((this._MaHLV != value))
				{
					this.OnMaHLVChanging(value);
					this.SendPropertyChanging();
					this._MaHLV = value;
					this.SendPropertyChanged("MaHLV");
					this.OnMaHLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHLV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHLV
		{
			get
			{
				return this._TenHLV;
			}
			set
			{
				if ((this._TenHLV != value))
				{
					this.OnTenHLVChanging(value);
					this.SendPropertyChanging();
					this._TenHLV = value;
					this.SendPropertyChanged("TenHLV");
					this.OnTenHLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NChar(10)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HuanLuyenVien_DoiBong", Storage="_DoiBongs", ThisKey="MaHLV", OtherKey="MaHLV")]
		public EntitySet<DoiBong> DoiBongs
		{
			get
			{
				return this._DoiBongs;
			}
			set
			{
				this._DoiBongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoiBongs(DoiBong entity)
		{
			this.SendPropertyChanging();
			entity.HuanLuyenVien = this;
		}
		
		private void detach_DoiBongs(DoiBong entity)
		{
			this.SendPropertyChanging();
			entity.HuanLuyenVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TranDau")]
	public partial class TranDau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTranDau;
		
		private string _LoaiTran;
		
		private string _MaTrongTai;
		
		private string _MaGiaiDau;
		
		private EntitySet<ChiTietTranDau> _ChiTietTranDaus;
		
		private EntityRef<GiaiDau> _GiaiDau;
		
		private EntityRef<TrongTai> _TrongTai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTranDauChanging(string value);
    partial void OnMaTranDauChanged();
    partial void OnLoaiTranChanging(string value);
    partial void OnLoaiTranChanged();
    partial void OnMaTrongTaiChanging(string value);
    partial void OnMaTrongTaiChanged();
    partial void OnMaGiaiDauChanging(string value);
    partial void OnMaGiaiDauChanged();
    #endregion
		
		public TranDau()
		{
			this._ChiTietTranDaus = new EntitySet<ChiTietTranDau>(new Action<ChiTietTranDau>(this.attach_ChiTietTranDaus), new Action<ChiTietTranDau>(this.detach_ChiTietTranDaus));
			this._GiaiDau = default(EntityRef<GiaiDau>);
			this._TrongTai = default(EntityRef<TrongTai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTranDau", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTranDau
		{
			get
			{
				return this._MaTranDau;
			}
			set
			{
				if ((this._MaTranDau != value))
				{
					this.OnMaTranDauChanging(value);
					this.SendPropertyChanging();
					this._MaTranDau = value;
					this.SendPropertyChanged("MaTranDau");
					this.OnMaTranDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTran", DbType="NVarChar(50)")]
		public string LoaiTran
		{
			get
			{
				return this._LoaiTran;
			}
			set
			{
				if ((this._LoaiTran != value))
				{
					this.OnLoaiTranChanging(value);
					this.SendPropertyChanging();
					this._LoaiTran = value;
					this.SendPropertyChanged("LoaiTran");
					this.OnLoaiTranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrongTai", DbType="NChar(10)")]
		public string MaTrongTai
		{
			get
			{
				return this._MaTrongTai;
			}
			set
			{
				if ((this._MaTrongTai != value))
				{
					if (this._TrongTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTrongTaiChanging(value);
					this.SendPropertyChanging();
					this._MaTrongTai = value;
					this.SendPropertyChanged("MaTrongTai");
					this.OnMaTrongTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaiDau", DbType="NChar(10)")]
		public string MaGiaiDau
		{
			get
			{
				return this._MaGiaiDau;
			}
			set
			{
				if ((this._MaGiaiDau != value))
				{
					if (this._GiaiDau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiaiDauChanging(value);
					this.SendPropertyChanging();
					this._MaGiaiDau = value;
					this.SendPropertyChanged("MaGiaiDau");
					this.OnMaGiaiDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TranDau_ChiTietTranDau", Storage="_ChiTietTranDaus", ThisKey="MaTranDau", OtherKey="MaTranDau")]
		public EntitySet<ChiTietTranDau> ChiTietTranDaus
		{
			get
			{
				return this._ChiTietTranDaus;
			}
			set
			{
				this._ChiTietTranDaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaiDau_TranDau", Storage="_GiaiDau", ThisKey="MaGiaiDau", OtherKey="MaGiaiDau", IsForeignKey=true)]
		public GiaiDau GiaiDau
		{
			get
			{
				return this._GiaiDau.Entity;
			}
			set
			{
				GiaiDau previousValue = this._GiaiDau.Entity;
				if (((previousValue != value) 
							|| (this._GiaiDau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaiDau.Entity = null;
						previousValue.TranDaus.Remove(this);
					}
					this._GiaiDau.Entity = value;
					if ((value != null))
					{
						value.TranDaus.Add(this);
						this._MaGiaiDau = value.MaGiaiDau;
					}
					else
					{
						this._MaGiaiDau = default(string);
					}
					this.SendPropertyChanged("GiaiDau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrongTai_TranDau", Storage="_TrongTai", ThisKey="MaTrongTai", OtherKey="MaTrongTai", IsForeignKey=true)]
		public TrongTai TrongTai
		{
			get
			{
				return this._TrongTai.Entity;
			}
			set
			{
				TrongTai previousValue = this._TrongTai.Entity;
				if (((previousValue != value) 
							|| (this._TrongTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrongTai.Entity = null;
						previousValue.TranDaus.Remove(this);
					}
					this._TrongTai.Entity = value;
					if ((value != null))
					{
						value.TranDaus.Add(this);
						this._MaTrongTai = value.MaTrongTai;
					}
					else
					{
						this._MaTrongTai = default(string);
					}
					this.SendPropertyChanged("TrongTai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietTranDaus(ChiTietTranDau entity)
		{
			this.SendPropertyChanging();
			entity.TranDau = this;
		}
		
		private void detach_ChiTietTranDaus(ChiTietTranDau entity)
		{
			this.SendPropertyChanging();
			entity.TranDau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrongTai")]
	public partial class TrongTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTrongTai;
		
		private string _TenTrongTai;
		
		private string _NgaySinh;
		
		private EntitySet<TranDau> _TranDaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTrongTaiChanging(string value);
    partial void OnMaTrongTaiChanged();
    partial void OnTenTrongTaiChanging(string value);
    partial void OnTenTrongTaiChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public TrongTai()
		{
			this._TranDaus = new EntitySet<TranDau>(new Action<TranDau>(this.attach_TranDaus), new Action<TranDau>(this.detach_TranDaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrongTai", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTrongTai
		{
			get
			{
				return this._MaTrongTai;
			}
			set
			{
				if ((this._MaTrongTai != value))
				{
					this.OnMaTrongTaiChanging(value);
					this.SendPropertyChanging();
					this._MaTrongTai = value;
					this.SendPropertyChanged("MaTrongTai");
					this.OnMaTrongTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrongTai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTrongTai
		{
			get
			{
				return this._TenTrongTai;
			}
			set
			{
				if ((this._TenTrongTai != value))
				{
					this.OnTenTrongTaiChanging(value);
					this.SendPropertyChanging();
					this._TenTrongTai = value;
					this.SendPropertyChanged("TenTrongTai");
					this.OnTenTrongTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NChar(10)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrongTai_TranDau", Storage="_TranDaus", ThisKey="MaTrongTai", OtherKey="MaTrongTai")]
		public EntitySet<TranDau> TranDaus
		{
			get
			{
				return this._TranDaus;
			}
			set
			{
				this._TranDaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TranDaus(TranDau entity)
		{
			this.SendPropertyChanging();
			entity.TrongTai = this;
		}
		
		private void detach_TranDaus(TranDau entity)
		{
			this.SendPropertyChanging();
			entity.TrongTai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDanhGia")]
	public partial class tDanhGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDG;
		
		private string _HoTen;
		
		private string _SDT;
		
		private string _Email;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDGChanging(string value);
    partial void OnMaDGChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public tDanhGia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDG", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDG
		{
			get
			{
				return this._MaDG;
			}
			set
			{
				if ((this._MaDG != value))
				{
					this.OnMaDGChanging(value);
					this.SendPropertyChanging();
					this._MaDG = value;
					this.SendPropertyChanged("MaDG");
					this.OnMaDGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(200)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tTaiKhoan")]
	public partial class tTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Quyen;
		
		private string _Email;
		
		private string _SoDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    #endregion
		
		public tTaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NChar(10)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(13)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VoteCLB")]
	public partial class VoteCLB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Idteam;
		
		private System.Nullable<int> _vote;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdteamChanging(string value);
    partial void OnIdteamChanged();
    partial void OnvoteChanging(System.Nullable<int> value);
    partial void OnvoteChanged();
    #endregion
		
		public VoteCLB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idteam", DbType="NChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Idteam
		{
			get
			{
				return this._Idteam;
			}
			set
			{
				if ((this._Idteam != value))
				{
					this.OnIdteamChanging(value);
					this.SendPropertyChanging();
					this._Idteam = value;
					this.SendPropertyChanged("Idteam");
					this.OnIdteamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vote", DbType="Int")]
		public System.Nullable<int> vote
		{
			get
			{
				return this._vote;
			}
			set
			{
				if ((this._vote != value))
				{
					this.OnvoteChanging(value);
					this.SendPropertyChanging();
					this._vote = value;
					this.SendPropertyChanged("vote");
					this.OnvoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
